#include "actor_profile.h"
#include "exported/positions.h"
#include "overlays/actors_emoteville/ovl_emoji_door/emoji_door.h"
#include "overlays/actors_emoteville/ovl_emoji_prop/emoji_prop.h"

#ifndef I3
#define I3(x, y, z) x, y, z
#endif

/*
 * DEF_ACTOR(actorId, position, rotation, params)
 */

DEF_ACTOR(ACTOR_EMOJI_DOOR, POS_DOOR, ROT_DOOR, EMOJI_DOOR_TO_MY_MAP)
DEF_ACTOR(ACTOR_EMOJI_PROP, POS_CHAIR, ROT_CHAIR, EMOJI_PROP_CHAIR)
DEF_ACTOR(ACTOR_EMOJI_PROP, POS_LIGHTBULB, ROT_LIGHTBULB, EMOJI_PROP_LIGHTBULB)
DEF_ACTOR(ACTOR_EMOJI_PROP, POS_SOFA, ROT_SOFA, EMOJI_PROP_SOFA)
DEF_ACTOR(ACTOR_EMOJI_PROP, POS_BED, ROT_BED, EMOJI_PROP_BED)
DEF_ACTOR(ACTOR_EMOJI_PROP, POS_FILE_CABINET_1, ROT_FILE_CABINET_1, EMOJI_PROP_FILE_CABINET_BIG)
DEF_ACTOR(ACTOR_EMOJI_PROP, POS_FILE_CABINET_2, ROT_FILE_CABINET_2, EMOJI_PROP_FILE_CABINET_BIG)
DEF_ACTOR(ACTOR_EMOJI_PROP, POS_FILE_CABINET_3, ROT_FILE_CABINET_3, EMOJI_PROP_FILE_CABINET_MEDIUM)
