#include "player.h"
#include "exported/positions.h"
#include "glue/glue_scene.h"

/*
 * DEF_SPAWN(name, room, position, yaw, params)
 */

DEF_SPAWN(INSIDE_HOUSE_SCENE_SPAWN_0, INSIDE_HOUSE_SCENE_ROOM_ROOM_0,
          POS_INSIDE_HOUSE_SCENE_SPAWN, YAW_INSIDE_HOUSE_SCENE_SPAWN,
          PLAYER_PARAMS(PLAYER_START_MODE_IDLE, PLAYER_START_BG_CAM_DEFAULT))
DEF_SPAWN(INSIDE_HOUSE_SCENE_SPAWN_UPSTAIRS_DEBUG, INSIDE_HOUSE_SCENE_ROOM_ROOM_0,
          POS_SPAWN_UPSTAIRS_DEBUG, YAW_SPAWN_UPSTAIRS_DEBUG,
          PLAYER_PARAMS(PLAYER_START_MODE_IDLE, PLAYER_START_BG_CAM_DEFAULT))
